In [227]:
import numpy as np
import pandas as pd
import random
from datetime import date


#np.random.seed(29) ----- used if multiple people are working on a project, you get the same "random" numbers

1. How likely is it that you roll doubles when rolling two dice?

In [66]:
# randomizing the rolling of two dice
die_one, die_two = random.randrange(1, 7), random.randrange(1, 7)
#die_two = random.randrange(1, 7)

print("The first roll is", die_one, "and the second roll is", die_two)
print("The probability of rolling doubles is appx:", round(1 / 6 * 100), '%')
if die_one == die_two:
    print("YOU ROLLED DOUBLES!!!!!!!")
    

The first roll is 1 and the second roll is 1
The probability of rolling doubles is appx: 17 %
YOU ROLLED DOUBLES!!!!!!!


In [119]:
n_rolls = nrows = 10_000
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_rolls * n_dice).reshape(nrows, ncols)
rolls

pd.DataFrame(rolls).apply(lambda row: row[0] == row[1], axis = 1).mean()


0.1684

2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [62]:
n_flips = nrows = 10000
n_coins = ncols = 8

flips = np.random.choice([0, 1], n_flips * n_coins).reshape(nrows, ncols)
flips

array([[0, 0, 1, ..., 1, 0, 0],
       [0, 1, 0, ..., 0, 1, 1],
       [0, 1, 0, ..., 1, 0, 1],
       ...,
       [0, 1, 1, ..., 0, 1, 1],
       [0, 0, 1, ..., 1, 1, 0],
       [1, 0, 1, ..., 0, 0, 1]])

In [63]:
sums_by_trial = flips.sum(axis=1)
sums_by_trial

array([3, 5, 5, ..., 5, 5, 5])

In [64]:
exact = sums_by_trial == 3
exact

array([ True, False, False, ..., False, False, False])

In [65]:
three_heads = exact.astype(int).mean()
three_heads

0.2241

3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [129]:
n_ds = nrows = 10000
n_wd = ncols = 2

billboards = np.random.choice([2, 4, 6, 7], n_ds * n_wd).reshape(nrows, ncols)
billboards

pd.DataFrame(billboards).apply(lambda row: row[0] & row[1] == 7, axis = 1).mean()

0.0675

4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [142]:
mean = 3
sd = 1.5
n_pts = nrows = 10_000
n_days = ncols = 5

poptarts_per_day = np.random.normal(mean, sd, n_pts * n_days).reshape(nrows, ncols)
poptarts_per_day
(
pd.DataFrame(poptarts_per_day).apply(lambda row: 
                                     row[0] + row[1] + row[2] + row[3] <= 17, axis = 1).mean()
)

#poptarts_per_week = poptarts_per_day.sum(axis = 1)
#poptarts_per_week



0.9543

5. Compare Heights

- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- Since you have means and standard deviations, you can use np.random.normal to generate observations.
- If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [149]:
mavg = 178
mstd = 8
wavg = 170
wstd = 6

obv = 10_000

m_height =  np.random.normal(mavg, mstd, obv)
m_height

w_height = np.random.normal(wavg, wstd, obv)
w_height

(w_height > m_height).mean()

0.2084

6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

- What is the probability that we observe an installation issue within the first 150 students that download anaconda?

- How likely is it that 450 students all download anaconda without an issue?

In [200]:
results = ['Clean', 'Corrupt']
obv = nrows = 10_000
students = ncols = 50
one_hundred_students = 100
one_fifty_students = 150
four_hundred_fifty = 450

conda = np.random.choice(results, size = (obv, students), p = [249/250, 1/250])
conda_two = np.random.choice(results, size = (obv, one_hundred_students), p = [249/250, 1/250])
conda_three = np.random.choice(results, size = (obv, one_fifty_students), p = [249/250, 1/250])
conda_four = np.random.choice(results, size = (obv, four_hundred_fifty), p = [249/250, 1/250])
conda

(conda == 'Clean').sum(axis = 1)

fifty_students = round(((conda == 'Clean').sum(axis=1) == 50).mean(), 2)
one_hundo = round(((conda_two == 'Clean').sum(axis=1) == 100).mean(), 2)
one_fifty = round(((conda_three == 'Clean').sum(axis=1) == 150).mean(), 2)
four_fifty = round(((conda_four == 'Clean').sum(axis=1) == 450).mean(), 2)
print('If fifty students download the software, roughly', fifty_students, 'percent of students will not have issues')
print('If fifty students download the software, roughly', one_hundo, 'percent of students will not have issues')
print('If fifty students download the software, roughly', one_fifty, 'percent of students will not have issues')
print('If fifty students download the software, roughly', four_fifty, 'percent of students will not have issues')

If fifty students download the software, roughly 0.82 percent of students will not have issues
If fifty students download the software, roughly 0.66 percent of students will not have issues
If fifty students download the software, roughly 0.55 percent of students will not have issues
If fifty students download the software, roughly 0.17 percent of students will not have issues


7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

- How likely is it that a food truck will show up sometime this week?

In [215]:
chance_of_truck = 0.7
n_days = 3
obv = 10_000
truck_present = np.random.random((obv ,n_days))
truck_present


array([[0.44904434, 0.79765585, 0.03195348],
       [0.53642198, 0.21668267, 0.02518537],
       [0.95604834, 0.97819358, 0.76903218],
       ...,
       [0.02203407, 0.49326098, 0.83402399],
       [0.9081563 , 0.41111351, 0.9087612 ],
       [0.02752291, 0.84052606, 0.13770575]])

In [216]:
lunch_time = (truck_present < chance_of_truck)
lunch_time

(lunch_time.sum(axis=1) == 0).mean()

0.0267

In [223]:
chance_of_truck = 0.7
n_days = 7
obv = 10_000
truck_present = np.random.random((obv, n_days))
truck_present

lunch_time = (truck_present < chance_of_truck)
lunch_time

(lunch_time.sum(axis=1) > 0).mean()

0.9999

8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [292]:
people = ncols = 23
obv = nrows = 10_000

random_day = random.randrange(1, 366)

samesies = np.random.choice(random_day, obv * people).reshape(nrows, ncols)
samesies

samesies = pd.DataFrame(samesies)
samesies


0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0      61  103  333  110  217  280  270   89  244  159  ...   91  325  284   
1      81   37  102  325  260   92  219  131  250   94  ...  239  309  222   
2     103   79  289  209  239  254  153  130  177   70  ...   84  181   50   
3     180  310   27  348   22  131  174  349  266  310  ...  191    6  256   
4     302  340  320   19  339  162  323  313  119  262  ...  349   88  266   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  194  130   29  330  273  291  162   29  217  182  ...  140   62  296   
9996   18   94  115  165  145  127  190  245  245    4  ...  288  227   82   
9997   77  132   43   93  114  215  105  263  323  225  ...  217  340  250   
9998   78   26  165  319   46  320  276   62  184  294  ...  257   74  187   
9999  180   70  326  167   11  270  232   59  289   62  ...  326   27   58   

       16   17   18   19   20   21   22  
0       9  275  273   27   77  133  212  
1      14  207  284  184  311  135  133  
2     223   19  207  169  308  298  337  
3      65   47  329  157  157  187  330  
4     199    5  131  217   31   51  276  
...   ...  ...  ...  ...  ...  ...  ...  
9995  340  158  151  209  199  292   98  
9996  349  237  121  332  260  142   68  
9997  228  107   72   69   27  201  209  
9998  302  342   47  328  350  126  259  
9999  270  348   17  289   90    3  273  

[10000 rows x 23 columns]

In [293]:
(samesies.nunique(axis=1) < 23).mean()

0.531